---
title: "Assignment 4"
author: "Corinna Hong"
date: "November 14, 2018"
output:
  word_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, echo=FALSE}

library(tidyverse)
library(tidyr)
library(vcdExtra)
library(car)
library(onewaytests)

```


```{r, include = FALSE}

# Read in data and put into tidy format

lobster_abundance <- read_csv("lobster_size_abundance.csv") %>% 
  as.data.frame(lobster_abundance) %>% # coerce tibbles into data.frame
  filter(COUNT != "0") %>% 
  expand.dft(freq = "COUNT") %>% # Give each lobster observation its own row
  select(YEAR, MONTH, DATE, SITE, SIZE)

lobster_traps <- read_csv("lobster_traps.csv") %>%
  filter(SITE == "IVEE"|SITE =="NAPL" |SITE == "AQUE"|SITE == "CARP" |SITE == "MOHK") %>% 
  select(YEAR, MONTH, DATE, SITE, TRAPS)

```

1. Lobster abundance and fishing pressure (2012 - 2017)

```{r}

# Create five graphs of each location with years on the x-axis and count of lobsters on y-axis

abundance_summary <- lobster_abundance %>% 
  group_by(SITE) %>% 
  count(YEAR) # Count how many observations there are in each year (data is grouped by site)
abundance_summary

abundance_col <- ggplot(abundance_summary, aes(x = YEAR, y = n)) +
  geom_col() +
  facet_wrap(~ SITE)
abundance_col

# Create graphs of trap buoys versus year at each site

trap_summary <- lobster_traps %>% 
  group_by(SITE) %>% 
  count(YEAR) # Count how many observations there are in each year (data is grouped by site)
trap_summary

trap_col <- ggplot(trap_summary, aes(x = YEAR, y = n)) +
  geom_col() +
  facet_wrap(~ SITE)
trap_col

```

2. Compare mean lobster size by site in 2017 

```{r}

# New dataframe for only year 2017

size_2017 <- lobster_abundance %>% 
  filter(YEAR == 2017) %>% 
  select(SITE, SIZE) 



# Data exploration

#Histograms

size_2017_hist <- ggplot(size_2017, aes(x = SIZE)) +
  geom_histogram() +
  facet_wrap(~ SITE, scale = "free") + # Create a histogram, split graphic visualization by site. Give each histogram its own y-axis scale
  theme_classic()
size_2017_hist


# QQ-Plots

size_2017_qq <- ggplot(size_2017, aes(sample = SIZE)) +
  geom_qq() +
  facet_wrap(~ SITE, scale = "free") + # Create a Q-Q plot, split graphic visualization by site. Give each Q-Q Plot its own y-axis scale
  theme_classic()
size_2017_qq



# Question: Is there a significant difference in mean lobster size between the five sites?

# H0: There is no significant difference in mean lobster size between the five sites
# HA: There is a significant difference in mean lobster size between the five sites



# Levene's Test 

# H0: There are no differences in varance across groups (variances are equal)
# HA: There are differences in variances across groups (variances are not equal)

lobster_levene <- leveneTest(SIZE ~ SITE, data = size_2017)
lobster_levene

# p < 0.05. Reject the null hypothesis. Our variances are differenct (Variances are not equal)



# What are the actual variances?

variances <- size_2017 %>% 
  group_by(SITE) %>% 
  summarize(
    mean = mean(SIZE),
    sd = sd(SIZE),
    variance = var(SIZE)
  )

# Our largest variance is less than 4x larger than our smallest variance



# ONE-WAY ANOVA:

lobster_aov <- aov(SIZE ~ SITE, data = size_2017)
lobster_sum_aov <- summary(lobster_aov)
lobster_sum_aov

lobster_ph <- TukeyHSD(lobster_aov)
lobster_ph

```



```{r}

lobster_box <- ggplot(size_2017, aes(x = SITE, y = SIZE)) +
  geom_boxplot(aes(fill = SITE, colour = SITE), alpha = 0.5, show.legend = FALSE) +
  ylab("Mean Lobster Size (mm)") +
  ggtitle("Lobster Sizes by Site (2017)") +
  theme(plot.title = element_text(hjust = 0.5)) +
  xlab("Site") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
lobster_box

```



```{r}

# Created separate datasets to attempt to merge them. 

lobster_counts <- lobster_abundance %>%
  group_by(SITE, YEAR) %>% 
  summarize(
    count = length(SIZE)
  )

lobster_line <- ggplot(lobster_counts, aes(x = YEAR, y = count, group = SITE)) + 
  geom_line(aes(linetype = SITE, color = SITE))+
  theme_classic()+
  geom_point(aes(color = SITE))+
  labs(x = "Year", y = "Lobster Abundance")
  
lobster_line
  
traps_counts <- lobster_traps %>% 
  group_by(SITE, YEAR) %>% 
  summarize(
    sum = sum(TRAPS))

traps_counts

traps_line <- ggplot(traps_counts, aes(x = YEAR, y = sum, group = SITE)) + 
  geom_line(aes(linetype = SITE, color = SITE))+
  theme_classic()+
  geom_point(aes(color = SITE))+
  labs(x = "Year", y = "Traps Adundance")

traps_line
```









